### ISSUE TITLE
Newer versions of dependencies

### ISSUE THREAD

**Issue by Dunedan** [adamziel/python_translate#2]
Currently the dependencies are hardcoded to specific versions. Please allow newer versions as well, as e.g. for `PyYAML` there is already a new version available.

**Comment by adamziel** [comment]
+1 I would love to! Could you issue a pull request please?

**Comment by adamziel** [comment]
Thanks!

**Comment by Dunedan** [comment]
It'd be cool if you could also release a new version with that change soon. :+1:

**Comment by adamziel** [comment]
https://pypi.python.org/pypi/python-translate/1.0.13
